name: Check Spellings

###########################
# Start the job on all PR #
###########################
on:
  pull_request:
    branches: [ master ]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Check Spelling
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install pyspelling
        sudo apt-get install aspell


      ##########################
      # Checkout the code base #
      ##########################
    - uses: actions/checkout@master
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}

    - name: Changed Files Exporter
      id: files
      uses: futuratrepadeira/changed-files@v3.2.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pattern: '^.*\.(md)$'

    - name: Detect Files
      uses: dorny/paths-filter@v2.6.0
      id: filter
      with:
        # Enable listing of files matching each filter.
        # Paths to files will be available in `${FILTER_NAME}_files` output variable.
        # Paths will be escaped and space-delimited.
        # Output is usable as command line argument list in linux shell
        list-files: shell

        # In this example changed files will be checked by linter.
        # It doesn't make sense to lint deleted files.
        # Therefore we specify we are only interested in added or modified files.
        filters: |
          python:
            - added|modified: '**.md'

      ####################################
      # Run Spellcheck against code base #
      ####################################
    - name: Check Spelling
      env:
        FILES: '${{ steps.files.outputs.files_updated }} ${{ steps.files.outputs.files_created }}'
      run: |
        str='./'
        echo "The Following files were changed or created:"
        echo $FILES
        for FILE in $FILES; do pyspelling -n Markdown -s FILE; done